name: 'Jekyll Deploy Action'
description: >
  A Github Action to deploy the Jekyll site conveniently for GitHub Pages
inputs:
  provider:
    description: 'The deploy provider'
    required: true
  owner:
    description: 'The deploy owner'
    required: false
  token:
    description: 'The deploy token'
    required: false
  credentials:
    description: 'The gcloud credentials'
    required: true
  repository:
    description: 'The deploy repository'
    required: false
  branch:
    description: 'The deploy branch'
    required: false
  actor:
    description: 'The github username creating the commit'
    required: false
  cname:
    description: 'The cname to use for the site'
    required: false
  bundler_ver:
    description: 'The Bundler version'
    required: false
  jekyll_baseurl:
    description: 'The Jekyll website baseurl'
    required: false
  pre_build_commands:
    description: 'The pre-build commands'
    required: false
branding:
  icon: 'command'
  color: 'red'
runs:
  using: composite
  steps:
    - name: 💎 Variables
      shell: bash
      id: variables
      run: |
        repo_name=${{ inputs.docker_hub_username }}/${{ inputs.image_name }}
        image_tag=${{ inputs.image_tag }}
        dev_image_tag="$image_tag"
        repo_ref="$repo_name:$image_tag"
        image_ref="${{ inputs.image_name }}:$image_tag"
        dev_repo_ref="$repo_name:$dev_image_tag"
        dev_image_ref="${{ inputs.image_name }}:$dev_image_tag"

        echo "repo_name=$repo_name" >> $GITHUB_OUTPUT
        echo "image_tag=$image_tag" >> $GITHUB_OUTPUT
        echo "dev_image_tag=$dev_image_tag" >> $GITHUB_OUTPUT
        echo "repo_ref=$repo_ref" >> $GITHUB_OUTPUT
        echo "image_ref=$image_ref" >> $GITHUB_OUTPUT
        echo "dev_repo_ref=$dev_repo_ref" >> $GITHUB_OUTPUT
        echo "dev_image_ref=$dev_image_ref" >> $GITHUB_OUTPUT

    - name: Write some user-data
      shell: powershell
      env:
        userdata: |
          #cloud-config
          locale: pt_BR
          users:
          - name: jdoe
            gecos: John Doe
            groups: [adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,netdev]
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
          write_files:
          - path: /etc/wsl.conf
            append: true
            content: |
              [user]
              default=jdoe
            packages: [hello]
      run: |
        $cloudinit = "${env:USERPROFILE}\.cloud-init\"

    - name: 💎 Set Credential
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ inputs.credentials }}

    - name: 💎 Authentication
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        install_components: 'alpha,cloud-datastore-emulator'

    - name: 💎 Self Hosted Runner
      shell: bash
      id: variables
      run: |
        gcloud info
