name: Docker Deploy Action

description: >
  🪂  A Github Action to deploy pages

branding:
  icon: 'command'
  color: 'yellow'

inputs:
  docker_hub_username:
    description: Username for Docker Hub
    default: ${{ github.actor }}
    required: false
  docker_hub_password:
    description: Docker Hub password
    required: true
  docker_hub_token:
    description: Docker Hub authentication token
    required: true
  initiate_pauli_sum:
    description: Build args
    required: false
    default: ""
  image_name:
    description: Tag to use for the new image
    default: ${{ github.action_repository }}
    required: true
  credentials:
    description: The Google cloud credentials
    required: true
  token:
    description: The Github personal token
    required: true
  gell_mann:
    description: 'The pre-build configuration'
    required: true

outputs:
  id:
    description: The site id
    value: ${{ steps.build.outputs.site_id}}

runs:
  using: composite
  steps:
    - name: Target Configuration
      if: runner.os != 'Windows'
      uses: eq19/eq19/.github/actions/3-hosted/4-parser@v1
      id: build
      with:
        hub_username: ${{ inputs.docker_hub_username }}
        hub_password: ${{ inputs.docker_hub_password }}
        hub_token: ${{ inputs.docker_hub_token }}
        credentials: ${{ inputs.credentials }}
        action_path: ${{ github.action_path }}
        image_name: ${{ inputs.image_name }}
        token: ${{ inputs.token }}

    - name: Profiling Feedback
      if: runner.os == 'Windows'
      uses: eq19/eq19/.github/actions/4-windows/4-parser@v1
      with:
        token: ${{ inputs.token }}
        image_name: ${{ inputs.image_name }}
        credentials: ${{ inputs.credentials }}
        action_path: ${GITHUB_ACTION_PATH//\\//}
        hub_token: ${{ inputs.docker_hub_token }} 
        hub_username: ${{ inputs.docker_hub_username }}
