name: 'Jekyll Deploy Action'
description: >
  A Github Action to deploy the Jekyll site conveniently for GitHub Pages
inputs:
  provider:
    description: 'The deploy provider'
    required: true
  owner:
    description: 'The deploy owner'
    required: false
  token:
    description: 'The deploy token'
    required: false
  credentials:
    description: 'The gcloud credentials'
    required: true
  repository:
    description: 'The deploy repository'
    required: false
  branch:
    description: 'The deploy branch'
    required: false
  actor:
    description: 'The github username creating the commit'
    required: false
  cname:
    description: 'The cname to use for the site'
    required: false
  bundler_ver:
    description: 'The Bundler version'
    required: false
  jekyll_baseurl:
    description: 'The Jekyll website baseurl'
    required: false
  pre_build_commands:
    description: 'The pre-build commands'
    required: false

branding:
  icon: 'command'
  color: 'red'

runs:
  using: composite
  steps:
    - name: 💎 Set Credential
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ inputs.credentials }}

    - name: 💎 Authentication
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        install_components: 'alpha,cloud-datastore-emulator'

    - name: 💎 Set parameters
      shell: bash
      id: variables
      run: |
        repo_name=${{ inputs.docker_hub_username }}/${{ inputs.image_name }}
        image_tag=${{ inputs.image_tag }}
        dev_image_tag="$image_tag"
        repo_ref="$repo_name:$image_tag"
        image_ref="${{ inputs.image_name }}:$image_tag"
        dev_repo_ref="$repo_name:$dev_image_tag"
        dev_image_ref="${{ inputs.image_name }}:$dev_image_tag"

        echo "repo_name=$repo_name" >> $GITHUB_OUTPUT
        echo "image_tag=$image_tag" >> $GITHUB_OUTPUT
        echo "dev_image_tag=$dev_image_tag" >> $GITHUB_OUTPUT
        echo "repo_ref=$repo_ref" >> $GITHUB_OUTPUT
        echo "image_ref=$image_ref" >> $GITHUB_OUTPUT
        echo "dev_repo_ref=$dev_repo_ref" >> $GITHUB_OUTPUT
        echo "dev_image_ref=$dev_image_ref" >> $GITHUB_OUTPUT

    - name: 💎 Self Hosted Runner
      shell: powershell
      env:
        userdata: |
          #cloud-config
          users:
          - default
          - uid: 2000
            name: runner
            groups: admin,adm,video,docker,google-sudoers

          write_files:
          - owner: root
            permissions: 0644
            path: /etc/systemd/system/runner.service
            content: |
              [Unit]
              Wants=gcr-online.target
              After=gcr-online.target
              Description=gcloud compute instances create instance-template
              [Service]
              Environment="HOME=/home/runner"
              ExecStartPre=/usr/bin/docker-credential-gcr configure-docker
              ExecStart=/usr/bin/docker run --rm --name myrunner -e RUNNER_NAME=Google-optimized-instance -e RUNNER_ORGANIZATION_URL=https://github.com/FeedMapping -e RUNNER_WORK_DIRECTORY=_work -e RUNNER_REPLACE_EXISTING=true -e GITHUB_ACCESS_TOKEN=${{ inputs.token }} -v /var/run/docker.sock:/var/run/docker.sock -v /mnt:/mnt eq19/setup
              ExecStop=/usr/bin/docker stop myrunner
              ExecStopPost=/usr/bin/docker rm myrunner

          runcmd:
          - systemctl daemon-reload
          - systemctl start runner.service
          - systemctl status runner.service

          bootcmd:
          - fsck.ext4 -tvy /dev/sdb1
          - mkdir -p /mnt/disks/Linux
          - mount -t ext4 -o discard,defaults /dev/sdb1 /mnt/disks/Linux

      run: |
        gcloud info
        [IO.File]::WriteAllText("cloud-config", "${env:userdata}")
        gcloud compute instances create instance-template --project=feedmapping --zone=us-central1-a --machine-type=e2-micro --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=project-owner@feedmapping.iam.gserviceaccount.com --scopes=https://www.googleapis.com/auth/cloud-platform --tags=https-server --create-disk=auto-delete=yes,boot=yes,device-name=instance-template,image=projects/cos-cloud/global/images/cos-101-17162-463-48,mode=rw,size=10,type=projects/feedmapping/zones/us-central1-a/diskTypes/pd-standard --create-disk=auto-delete=yes,device-name=disk-1,image=projects/ml-images/global/images/c0-deeplearning-common-cpu-v20230925-debian-10,mode=rw,name=disk-1,size=50,type=projects/feedmapping/zones/us-central1-a/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --labels=goog-ec-src=vm_add-gcloud --reservation-affinity=any
